# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Skwad' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Skwad
pod 'Firebase/Core'
pod 'Firebase/Database'

  target 'SkwadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SkwadUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
